CREATE DATABASE PESSOAS;
GO

USE PESSOAS;
GO

CREATE TABLE PESSOA (
    idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomePessoa VARCHAR(75) NOT NULL
);
GO

CREATE TABLE CNH (
   idCnh INT PRIMARY KEY IDENTITY(1,1),
   idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa) NOT NULL,
   descricao VARCHAR(70) NOT NULL
);
GO

CREATE TABLE TELEFONE (
   idTelefone INT PRIMARY KEY IDENTITY(1,1),
   idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa) NOT NULL,
   numeroTelefone CHAR(11) NOT NULL
);
GO

CREATE TABLE EMAIL (
	idEmail INT PRIMARY KEY IDENTITY(1,1),
	enderecoEmail VARCHAR(250) NOT NULL UNIQUE,
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa) NOT NULL
);
GO